language: android
script: ./gradlew clean app:jacoco
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
